name: Build Windows

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'beta'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows
        run: flutter build windows
      
      - name: Create Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Windows Build
          path: build/windows/ 
